"""
Deterministic Demo Runner for Prudential Insurance Investigation
================================================================
Replays a fixed STOLI investigation scenario over WebSocket.
No LLM / Bedrock calls are made.

Scenario
--------
1.  Orchestrator routes to Investigation (Phase: investigate)
2.  Investigation scans agents, profiles AGT-0042 cluster
3.  Orchestrator routes to Dossier (Phase: compile)
4.  Dossier REJECTS — insufficient evidence (missing network analysis)
5.  Investigation traces STOLI ring connections
6.  Orchestrator routes to Dossier (Phase: compile)
7.  Dossier REJECTS AGAIN — missing regulatory citations
8.  Investigation gathers regulatory rules + peer comparisons
9.  Orchestrator routes to Dossier (Phase: compile)
10. Dossier ACCEPTS — evidence sufficient → produces final dossier
"""

import asyncio
import time
import os
from datetime import datetime

DEMO_FINAL_DOSSIER = r"""# STOLI/IOLI INVESTIGATION DOSSIER

**Hypothesis**: Coordinated STOLI ring operating through trust-owned policies with premium financing
**Case Type**: STOLI
**Generated**: {date}
**Status**: Evidence Sufficient - Ready for Action

---

## EXECUTIVE SUMMARY

Investigation identified a suspected STOLI ring involving 5 agents centered around AGT-0042. The ring utilized trust-owned policies with premium financing through Meridian Trust Holdings LLC and Pacific Premium Finance Corp. Total face amount exposure: **$85,000,000**. 8 independent evidence points with quantitative significance and regulatory basis established.

---

## ENTITIES INVOLVED

### Entity 1: AGT-0042
- **Type**: Agent (Primary Subject)
- **Anomaly Score**: 0.85
- **Total Face Amount**: $42,500,000
- **Trust-Owned Policies**: 65%
- **Premium-Financed**: 58%
- **Region**: Northeast

### Entity 2: AGT-0043
- **Type**: Agent (Ring Member)
- **Anomaly Score**: 0.78
- **Total Face Amount**: $18,200,000

### Entity 3: AGT-0044
- **Type**: Agent (Ring Member)
- **Anomaly Score**: 0.72
- **Total Face Amount**: $12,800,000

### Entity 4: Meridian Trust Holdings LLC
- **Type**: Trust Entity (Beneficiary)
- **Connected Policies**: 28
- **Role**: Common trust beneficiary across ring

### Entity 5: Pacific Premium Finance Corp
- **Type**: Premium Finance Entity
- **Connected Policies**: 22
- **Role**: Premium financing for trust-owned policies

---

## EVIDENCE

1. AGT-0042 anomaly score 0.85 — 3.2 standard deviations above peer average for trust_owned_pct
2. Cluster of 5 agents with interconnected trust-owned policies through Meridian Trust Holdings LLC
3. 65% of AGT-0042's policies are trust-owned vs peer average of 4% (z-score: 4.1)
4. Premium financing rate 58% through Pacific Premium Finance Corp vs peer average 2%
5. Average face amount $2.8M per policy vs peer average $350K — 8x multiplier
6. 28 policies connected to same trust beneficiary across 3 agents
7. Network density 3.8 among ring members — highly interconnected
8. Replacement rate 0.42 for AGT-0042 vs peer average 0.08 (z-score: 3.5)

---

## NETWORK ANALYSIS

- **Connected Entities**: 12
- **Connection Density**: 3.8
- **Ring Members**: AGT-0042, AGT-0043, AGT-0044, AGT-0045, AGT-0046
- **Common Trust**: Meridian Trust Holdings LLC
- **Common Finance**: Pacific Premium Finance Corp

---

## REGULATORY VIOLATIONS

### STOLI-001: Stranger-Originated Life Insurance Detection
Trust-owned policies originated by agents with no insurable interest between policyholder and trust beneficiary. Violates state insurable interest requirements.

### STOLI-002: Premium Financing Red Flags
Third-party premium financing through single entity for clustered high-face-amount policies. Pattern consistent with STOLI scheme.

### AGENT-001: Suitability and Replacement Analysis
Agent replacement rate 0.42 (42%) — far exceeds acceptable threshold. Pattern of churning existing policies for trust-owned replacements.

---

## PRECEDENT CASES

- **DOI-2024-0223**: STOLI Ring — 4 agents, 28 policies, $85M face. Policies voided, licenses revoked.
- **DOI-2025-0089**: Agent churning — 45% replacement rate, 67 affected policyholders. License suspended.

---

## FINANCIAL IMPACT

- **Total Face Amount**: $85,000,000.00
- **Gross Exposure**: $85,000,000.00
- **Recovery Rate**: 90%
- **Confidence**: 0.95
- **Net Expected Recovery**: **$72,675,000.00**
- **Recommended Action**: VOID POLICIES - Lack of insurable interest

---

## RECOMMENDATIONS

1. Void all trust-owned policies originated by ring members for lack of insurable interest
2. Refer AGT-0042, AGT-0043, AGT-0044, AGT-0045, AGT-0046 to state DOI for license review
3. Report Meridian Trust Holdings LLC and Pacific Premium Finance Corp to regulators
4. File SARs for suspicious premium financing transactions
5. Review all policies sold by ring members in the last 3 years

---
*Generated by ARIA - Prudential Insurance Investigation Copilot*
"""


def _send(ws, loop, event_type, data):
    from api import ws_send
    asyncio.run_coroutine_threadsafe(ws_send(ws, event_type, data), loop)
    time.sleep(0.05)


def _log_and_send(ws, loop, agent, message, delay=0.3):
    _send(ws, loop, "log", {"agent": agent, "message": message})
    # Write to demo log file
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    logs_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "logs")
    os.makedirs(logs_dir, exist_ok=True)
    log_path = os.path.join(logs_dir, f"investigation_demo_{timestamp}.txt")
    try:
        with open(log_path, "a", encoding="utf-8") as f:
            f.write(f"{agent}\n{message}\n")
    except Exception:
        pass
    time.sleep(delay)


def run_demo_investigation_sync(ws, loop):
    """Replay a scripted STOLI investigation. Called from a thread."""

    s = lambda et, d: _send(ws, loop, et, d)
    log = lambda a, m, delay=0.3: _log_and_send(ws, loop, a, m, delay)

    s("status", {"message": "Investigation starting (demo mode)..."})
    time.sleep(0.5)

    # ===== ITERATION 1: Orchestrator → Investigation =====
    s("node_enter", {"node": "orchestrator", "iteration": 1})
    log("Orchestrator", "--- Iteration 1 | Current phase: start ---")
    log("Orchestrator", "Calling LLM for routing decision...")
    time.sleep(0.8)
    log("Orchestrator", "LLM responded in 1.2s")
    log("Orchestrator", "Phase transition: start -> investigate")
    s("phase_change", {"phase": "investigate", "loop_count": 1})
    s("node_exit", {"node": "orchestrator", "elapsed": 1.5, "phase": "investigate", "loop_count": 1})

    # ===== ITERATION 2: Investigation — initial scan =====
    s("node_enter", {"node": "investigation", "iteration": 2})
    log("Investigation", "Starting investigation sub-agent (7 tools available)...")
    log("Investigation", "Invoking LLM + tool loop...")

    log("tool", "tool:scan_suspicious_entities -> Scanning (anomaly > 0.5)...")
    time.sleep(1.0)
    log("tool", "tool:scan_suspicious_entities -> Found 8 high-anomaly entities (0.3s)")

    log("tool", "tool:profile_agent -> Profiling AGT-0042...")
    time.sleep(0.8)
    log("tool", "tool:profile_agent -> Score: 0.85, 65% trust-owned, 58% premium-financed, face=$42.5M")

    log("tool", "tool:profile_agent -> Profiling AGT-0043...")
    time.sleep(0.6)
    log("tool", "tool:profile_agent -> Score: 0.78, 52% trust-owned, face=$18.2M")

    log("tool", "tool:profile_agent -> Profiling AGT-0044...")
    time.sleep(0.6)
    log("tool", "tool:profile_agent -> Score: 0.72, 45% trust-owned, face=$12.8M")

    log("tool", "tool:get_policy_details -> Fetching policies for AGT-0042...")
    time.sleep(0.5)
    log("tool", "tool:get_policy_details -> 10 policies returned — avg face $2.8M, 7 trust-owned")

    log("Investigation", "Sub-agent finished in 8.2s | Tool calls made: 5")
    log("Investigation", "Summary: Identified high-anomaly agent cluster (AGT-0042/43/44) with elevated trust ownership and premium financing rates...")

    s("node_exit", {"node": "investigation", "elapsed": 10.0,
       "findings_preview": "Identified agent cluster AGT-0042 (0.85), AGT-0043 (0.78), AGT-0044 (0.72) with abnormal trust ownership and premium financing patterns..."})

    # ===== ITERATION 3: Orchestrator → Dossier =====
    s("node_enter", {"node": "orchestrator", "iteration": 3})
    log("Orchestrator", "--- Iteration 2 | Current phase: investigate ---")
    log("Orchestrator", "Phase transition: investigate -> compile")
    s("phase_change", {"phase": "compile", "loop_count": 2})
    s("node_exit", {"node": "orchestrator", "elapsed": 11.5, "phase": "compile", "loop_count": 2})

    # ===== ITERATION 4: Dossier REJECTS =====
    s("node_enter", {"node": "dossier", "iteration": 4})
    log("Dossier", "Starting dossier sub-agent (5 tools available)...")
    log("Dossier", "Invoking LLM + tool loop (evidence assessment)...")

    log("tool", "tool:assess_evidence -> Assessing 'STOLI ring' (3 points)...")
    time.sleep(0.8)
    log("tool", "tool:assess_evidence -> INSUFFICIENT (2 passed, 2 failed)")
    log("tool", "tool:assess_evidence -> Missing: network_evidence, regulatory_basis")

    log("Dossier", "Evidence assessed as INSUFFICIENT - looping back to investigation")
    s("dossier_rejected", {
        "message": "Dossier rejected — evidence INSUFFICIENT. Missing network analysis and regulatory citations.",
        "evidence_gaps": "Need network/ring analysis showing STOLI connections. Need regulatory rule citations (STOLI-001, STOLI-002)."
    })
    s("node_exit", {"node": "dossier", "elapsed": 14.0, "evidence_sufficient": False})

    # ===== ITERATION 5: Orchestrator → Investigation (loop back) =====
    s("node_enter", {"node": "orchestrator", "iteration": 5})
    log("Orchestrator", "--- Iteration 3 | Current phase: investigate ---")
    log("Orchestrator", "Evidence INSUFFICIENT - looping back to investigation")
    log("Orchestrator", "Phase transition: investigate -> investigate")
    s("phase_change", {"phase": "investigate", "loop_count": 3})
    s("node_exit", {"node": "orchestrator", "elapsed": 15.5, "phase": "investigate", "loop_count": 3})

    # ===== ITERATION 6: Investigation — network + ring analysis =====
    s("node_enter", {"node": "investigation", "iteration": 6})
    log("Investigation", "Starting investigation sub-agent (addressing evidence gaps)...")
    log("Investigation", "Evidence gaps: need network/ring analysis + regulatory citations")

    log("tool", "tool:find_connections -> Traversing graph from AGT-0042 (depth=2)...")
    time.sleep(1.0)
    log("tool", "tool:find_connections -> 12 connected entities, density=3.8")

    log("tool", "tool:find_stoli_ring -> Searching rings (anomaly >= 0.5, min=3)...")
    time.sleep(1.2)
    log("tool", "tool:find_stoli_ring -> Found 1 ring: 5 entities, avg_anomaly=0.78, density=3.8")

    log("tool", "tool:compare_agent_to_peers -> Comparing AGT-0042 on trust_owned_pct...")
    time.sleep(0.6)
    log("tool", "tool:compare_agent_to_peers -> Value: 0.65, peer_avg: 0.04, z-score: 4.1")

    log("tool", "tool:compare_agent_to_peers -> Comparing AGT-0042 on replacement_rate...")
    time.sleep(0.5)
    log("tool", "tool:compare_agent_to_peers -> Value: 0.42, peer_avg: 0.08, z-score: 3.5")

    log("Investigation", "Sub-agent finished in 6.8s | Tool calls made: 4")
    s("node_exit", {"node": "investigation", "elapsed": 23.0,
       "findings_preview": "STOLI ring confirmed: 5 agents, density 3.8, connected through Meridian Trust Holdings LLC. Trust ownership z-score 4.1, replacement rate z-score 3.5..."})

    # ===== ITERATION 7: Orchestrator → Dossier =====
    s("node_enter", {"node": "orchestrator", "iteration": 7})
    log("Orchestrator", "--- Iteration 4 | Current phase: investigate ---")
    log("Orchestrator", "Phase transition: investigate -> compile")
    s("phase_change", {"phase": "compile", "loop_count": 4})
    s("node_exit", {"node": "orchestrator", "elapsed": 24.5, "phase": "compile", "loop_count": 4})

    # ===== ITERATION 8: Dossier REJECTS AGAIN =====
    s("node_enter", {"node": "dossier", "iteration": 8})
    log("Dossier", "Starting dossier sub-agent...")

    log("tool", "tool:assess_evidence -> Assessing 'STOLI ring' (6 points)...")
    time.sleep(0.8)
    log("tool", "tool:assess_evidence -> INSUFFICIENT (3 passed, 1 failed)")
    log("tool", "tool:assess_evidence -> Missing: regulatory_basis — need rule citations")

    log("Dossier", "Evidence INSUFFICIENT — missing regulatory citations")
    s("dossier_rejected", {
        "message": "Dossier rejected — still INSUFFICIENT. Need regulatory rule citations.",
        "evidence_gaps": "All quantitative and network evidence present. Missing regulatory rule search (STOLI-001, STOLI-002, AGENT-001)."
    })
    s("node_exit", {"node": "dossier", "elapsed": 27.0, "evidence_sufficient": False})

    # ===== ITERATION 9: Orchestrator → Investigation =====
    s("node_enter", {"node": "orchestrator", "iteration": 9})
    log("Orchestrator", "--- Iteration 5 | Current phase: investigate ---")
    log("Orchestrator", "Phase transition: investigate -> investigate")
    s("phase_change", {"phase": "investigate", "loop_count": 5})
    s("node_exit", {"node": "orchestrator", "elapsed": 28.5, "phase": "investigate", "loop_count": 5})

    # ===== ITERATION 10: Investigation — regulatory rules =====
    s("node_enter", {"node": "investigation", "iteration": 10})
    log("Investigation", "Gathering regulatory citations to complete evidence...")

    log("tool", "tool:get_agent_activity_history -> Pulling 12-month history for AGT-0042...")
    time.sleep(0.8)
    log("tool", "tool:get_agent_activity_history -> 12 months, avg 4.2 policies/month, trust % increasing over time")

    log("Investigation", "Sub-agent finished in 2.5s | Tool calls made: 1")
    s("node_exit", {"node": "investigation", "elapsed": 31.5,
       "findings_preview": "Activity history shows escalating trust-owned policy pattern. Regulatory rules STOLI-001, STOLI-002, AGENT-001 applicable..."})

    # ===== ITERATION 11: Orchestrator → Dossier (final) =====
    s("node_enter", {"node": "orchestrator", "iteration": 11})
    log("Orchestrator", "--- Iteration 6 | Current phase: investigate ---")
    log("Orchestrator", "Phase transition: investigate -> compile")
    s("phase_change", {"phase": "compile", "loop_count": 6})
    s("node_exit", {"node": "orchestrator", "elapsed": 33.0, "phase": "compile", "loop_count": 6})

    # ===== ITERATION 12: Dossier ACCEPTS =====
    s("node_enter", {"node": "dossier", "iteration": 12})
    log("Dossier", "Starting dossier sub-agent...")

    log("tool", "tool:assess_evidence -> Assessing 'STOLI ring' (8 points)...")
    time.sleep(0.8)
    log("tool", "tool:assess_evidence -> SUFFICIENT (5 passed, 0 failed)")

    log("tool", "tool:search_insurance_rules -> Searching rules for STOLI...")
    time.sleep(0.6)
    log("tool", "tool:search_insurance_rules -> Found 3 applicable rules")

    log("tool", "tool:find_similar_cases -> Looking up precedents for stoli_ring...")
    time.sleep(0.5)
    log("tool", "tool:find_similar_cases -> Found 2 precedent cases")

    log("tool", "tool:estimate_financial_impact -> STOLI: 5 entities, risk=0.85...")
    time.sleep(0.5)
    log("tool", "tool:estimate_financial_impact -> Exposure: $85M, net recovery: $72.7M")

    log("tool", "tool:compile_dossier -> Generating dossier...")
    time.sleep(1.0)
    log("tool", "tool:compile_dossier -> STOLI dossier generated (2847 chars)")

    log("Dossier", "Evidence assessed as SUFFICIENT")
    s("dossier_accepted", {"message": "Evidence SUFFICIENT — dossier compiled."})
    s("node_exit", {"node": "dossier", "elapsed": 38.0, "evidence_sufficient": True})

    # ===== Final orchestrator → done =====
    s("node_enter", {"node": "orchestrator", "iteration": 13})
    log("Orchestrator", "Phase transition: compile -> done")
    s("phase_change", {"phase": "done", "loop_count": 7})
    s("node_exit", {"node": "orchestrator", "elapsed": 39.0, "phase": "done", "loop_count": 7})

    # ===== Complete =====
    dossier_text = DEMO_FINAL_DOSSIER.format(date=datetime.now().strftime("%Y-%m-%d %H:%M"))

    s("investigation_complete", {
        "iterations": 13,
        "total_time": 39.0,
        "phase": "done",
        "loop_count": 7,
        "evidence_sufficient": True,
        "dossier": dossier_text,
        "findings": {
            "last_investigation": "STOLI ring confirmed: AGT-0042 cluster, 5 agents, Meridian Trust, Pacific Premium Finance. Z-scores: trust_owned 4.1, replacement_rate 3.5. Rules: STOLI-001, STOLI-002, AGENT-001.",
        },
    })
